### ISSUE TITLE
[Request] Add DiffAugment option

### ISSUE THREAD

**Issue by YukiSakuma** [pbaylies/stylegan2#12]
ref:https://github.com/mit-han-lab/data-efficient-gans

And could you also add this?
https://github.com/genforce/sefa

Still no official code release but I saw an implementation of it (from:https://github.com/rosinality/stylegan2-pytorch) but I can't get this stylegan2-pytorch working on my computer even with latest pytorch, so I would appreciate if this TF repo could implement(or convert) it instead.

**Comment by eps696** [comment]
@pbaylies @YukiSakuma 
i've added the first to my setup, one may copy it from there https://github.com/eps696/stylegan2
works like a charm indeed

as for pytorch stylegan2, the key for me was proper setup of the environment variables (i'm on windows tho), such as:
```
set VS=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023
set SDKdir=C:\Program Files (x86)\Windows Kits\10
set SDKnum=10.0.17763.0
set PY=C:\Users\eps\AppData\Local\Programs\Python\Python35

set torch=%PY%\Lib\site-packages\torch

set INCLUDE=%INCLUDE%;%VS%\include
set INCLUDE=%INCLUDE%;%SDKdir%\include\%SDKnum%\ucrt
set INCLUDE=%INCLUDE%;%SDKdir%\include\%SDKnum%\shared

set MYLIB=
set MYLIB=%MYLIB%;%VS%\lib\x64
set MYLIB=%MYLIB%;%SDKdir%\Lib\%SDKnum%\ucrt\x64
set MYLIB=%MYLIB%;%SDKdir%\Lib\%SDKnum%\um\x64

set CUDA_HOME=%CUDA_PATH%
set LIB=%LIB%;%MYLIB%
```

also settings in `fused_act.py` and `upfirdn2d.py`, right after imports:
```
cxx_args = ['/w']
nvcc_args = [
    '--disable-warnings',
    '-gencode', 'arch=compute_60,code=sm_60', # tesla p100
    '-gencode', 'arch=compute_61,code=sm_61', # 10xx
    '-gencode', 'arch=compute_75,code=sm_75', # rtx 20xx
    '-gencode', 'arch=compute_75,code=compute_75'
]
module_path = os.path.dirname(__file__)
fused = load('fused',
    sources=[
        os.path.join(module_path, 'fused_bias_act.cpp'),
        os.path.join(module_path, 'fused_bias_act_kernel.cu'),
    ],
    extra_cflags = cxx_args, # c++ args from above 
    extra_cuda_cflags = nvcc_args, # nvcc args from above 
    extra_ldflags = ['c10_cuda.lib'],
)

```

**Comment by YukiSakuma** [comment]
@eps696 I'll take a look at your repo but on the 2nd part do I really have to use MSVC 2017? Because the one I have is 2019 and I keep getting the ninja error and the failed fused and except for MSVC 2019 I believe I satisfy the rest of the requirements from my conda env that I installed:
pytorch 1.3.1
cuda 10.1

I'm on windows too

and about editing `upfirdn2d.py` did you mean it this instead

```
cxx_args = ['/w']
nvcc_args = [
    '--disable-warnings',
    '-gencode', 'arch=compute_60,code=sm_60',  # tesla p100
    '-gencode', 'arch=compute_61,code=sm_61',  # 10xx
    '-gencode', 'arch=compute_75,code=sm_75',  # rtx 20xx
    '-gencode', 'arch=compute_75,code=compute_75'
]
module_path = os.path.dirname(__file__)
upfirdn2d_op = load(
    "upfirdn2d",
    sources=[
        os.path.join(module_path, "upfirdn2d.cpp"),
        os.path.join(module_path, "upfirdn2d_kernel.cu"),
    ],
    extra_cflags=cxx_args,  # c++ args from above
    extra_cuda_cflags=nvcc_args,  # nvcc args from above
    extra_ldflags=['c10_cuda.lib'],
)

```

**Comment by eps696** [comment]
@YukiSakuma 
1) you may try replacing the env settings `VS` and `SDKnum` (and maybe `SDKdir`) according to your version (2019), so that `INCLUDE` and `MYLIB` point to existing paths. i use VS 2017 because of compatibility recommendation (for Tensorflow or smth else, can't tell at once). you may also need to change `PY` according to your python setup (conda or just another path) - the rest should hopefully work (tested on VS 2015 and 2017)
2) sure, thanks for noticing (posted in a hurry, sorry)
