### ISSUE TITLE
Bug: the discriminator is using the generator's learning rate

### ISSUE THREAD

**Issue by aydao** [pbaylies/stylegan2#5]
Credit to this bug goes to @shawwn [who reported it on Twitter](https://twitter.com/theshawwn/status/1230022825538248704). I know you're already aware of the issue, but thought it important to document here for anyone searching for it.

Basically, the learning rate for the discriminator can be written to, but it is never read. Instead, the lrate_in used by both networks reads from G_lrate, [here](https://github.com/pbaylies/stylegan2/blame/master/training/training_loop.py#L313).

Also, once this is fixed, a quality of life feature I'd like to suggest would be to change the --lr argument for run_training.py to two new ones that set the G and D learning rates separately. Something like --lrG=0.003 and --lrD=0.0015 would be handy.

**Comment by 8secz-johndpope** [comment]
see @skyflynil  93e2da16dd78c6ed9dec0bf700e620ae1a142b5c
